
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployment
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - dbishpa.my.shpa
  resources:
  - shpas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbishpa.my.shpa
  resources:
  - shpas/status
  verbs:
  - get
  - patch
  - update
