# permissions for end users to edit shpas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shpa-editor-role
rules:
- apiGroups:
  - apps
  - extensions
  resources:
  - replicasets/scale
  - deployments/scale
  - statefulsets/scale
  verbs:
  - update
  - get
- apiGroups:
  - apps
  - extensions
  resourceNames:
  - shpas
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - dbishpa.my.shpa
  resources:
  - shpas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbishpa.my.shpa
  resources:
  - shpas/status
  verbs:
  - get


