apiVersion: dbishpa.my.shpa/v1
kind: SHPA
metadata:
  name: shpa-v3
spec:
  maxReplicas: 20
  minReplicas: 4
  tolerance: 1
  readinessDelay: 10
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: shpa-cp
  metrics:
    - type: Resource
      resource:
        highWatermark: "80m"
        lowWatermark: "30m"
        name: cpu
        metricSelector:
          matchLabels:
            app: shpa-cp # Match the targeted nginx pods using the pod label app=nginx
