apiVersion: dbishpa.my.shpa/v1
kind: SHPA
metadata:
  name: shpa-sample
spec:
  downscaleForbiddenWindowSeconds: 60
  upscaleForbiddenWindowSeconds: 30
  scaleDownLimitFactor: 30
  scaleUpLimitFactor: 50
  minReplicas: 4
  maxReplicas: 9
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: shpa-ss
  metrics:
    - external:
        highWatermark: 100m
        lowWatermark: 50m
        metricName: cpu
        metricSelector:
          matchLabels:
            kubernetes_cluster: mycluster
            service: billing
            short_image: billing-app
      type: External
  tolerance: 1