apiVersion: dbishpa.my.shpa/v1
kind: SHPA
metadata:
  name: shpa-shpa
spec:
  maxReplicas: 20
  minReplicas: 4
  tolerance: 1
  readinessDelay: 10
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: shpa-ss
  metrics:
  - type: Resource
    resource:
      highWatermark: "100m"
      lowWatermark: "50m"
      name: cpu
      metricSelector:
        matchLabels:
          app: shpa-ss # Match the targeted nginx pods using the pod label app=nginx
